site_name: QSTrader-CN 使用指南
site_url: http://nymath.com/
repo_url: https://github.com/nymath/QSTrader-CN

nav:
    - QuickStart: index.md
    - Tests: Test.md
    - Modules I(Makert & Strategy): ch1.md
    - Modules II (Order): ch2.md
    - Modules III(Portfolio & Execution): ch3.md
    - Modules IV (Backtest): ch4.md
    - Examples: che.md
    - Reference: ref.md

theme: 
  name: material
  features:
    - content.code.copy
    - content.code.annotate 
    - content.tabs.link
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - navigation.tracking
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - glightbox


markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript: 
  - https://cdn.jsdelivr.net/npm/mermaid@8.4.4/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
